import "./globals.css"
import Header from "$/main/Header"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
// it renders the page
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
